"""Fetch curriculum documents from Supabase Storage and cache their text.

The crew YAML files (notes_crew, quiz_crew, assignment_crew) reference docs
by filename. Those filenames live in the public ``curriculum`` bucket on
Supabase Storage as pre-extracted ``.txt`` files; this module turns a
filename into a public URL, downloads it, and caches the result for the
lifetime of the process.

When the caller passes ``subtopic=...``, we first try a per-subtopic excerpt
file (``<book-slug>__<subtopic-slug>.txt``) generated by the offline
pipeline at ``scripts/build_curriculum_excerpts.py``. If the excerpt isn't
in the bucket yet (404/empty), we fall back to the whole-book filename so
generation still works while the pipeline catches up.

Cache is in-memory and per-process, keyed by the physical filename actually
fetched, so excerpt and fallback paths share entries cleanly. Single-instance
Railway is fine for now; when we scale to multiple replicas, replace
``_CACHE`` with Redis behind the same interface.
"""

from __future__ import annotations

import re
import time
import urllib.parse

from app.config import get_settings
from app.core.logging import get_logger, log_extra
from app.services.file_fetch import fetch_plain_text

BUCKET = "curriculum"
SLUG_MAX_LEN = 80

_CACHE: dict[str, str] = {}

logger = get_logger(__name__)


def _public_url(filename: str) -> str:
    base = get_settings().supabase_url.rstrip("/")
    encoded = urllib.parse.quote(filename, safe="")
    return f"{base}/storage/v1/object/public/{BUCKET}/{encoded}"


def _subtopic_slug(text: str) -> str:
    """Filename-safe slug: lowercase, non-alnum runs collapsed to '-', max 80 chars.

    Imported by ``scripts/build_curriculum_excerpts.py`` so pipeline-side and
    runtime-side slugs always match.
    """
    s = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return s[:SLUG_MAX_LEN].rstrip("-")


def _excerpt_filename(book_filename: str, subtopic: str) -> str:
    """Build the per-subtopic excerpt filename in the bucket.

    Example: ("How to Read a Film_ Movies, Media, and Beyond.txt", "film analysis")
        -> "how-to-read-a-film-movies-media-and-beyond__film-analysis.txt"
    """
    base = book_filename[:-4] if book_filename.lower().endswith(".txt") else book_filename
    return f"{_subtopic_slug(base)}__{_subtopic_slug(subtopic)}.txt"


async def _fetch_with_cache(physical_filename: str, *, kind: str) -> str:
    """Fetch + cache one bucket file. ``kind`` is "excerpt" or "doc" for logging.

    Excerpt misses are expected (pipeline hasn't run for that pair yet) and
    log at INFO; whole-doc misses log at WARNING because something's actually
    wrong with the upload.
    """
    if physical_filename in _CACHE:
        cached = _CACHE[physical_filename]
        logger.info(
            "curriculum.cache_hit",
            extra=log_extra(
                doc=physical_filename, kind=kind, chars=len(cached), empty=not cached
            ),
        )
        return cached

    url = _public_url(physical_filename)
    started = time.perf_counter()
    try:
        text = await fetch_plain_text(url)
        duration_ms = round((time.perf_counter() - started) * 1000, 2)
        if text:
            logger.info(
                "curriculum.fetch_ok",
                extra=log_extra(
                    doc=physical_filename,
                    kind=kind,
                    chars=len(text),
                    duration_ms=duration_ms,
                ),
            )
        else:
            log = logger.info if kind == "excerpt" else logger.warning
            log(
                "curriculum.fetch_empty",
                extra=log_extra(
                    doc=physical_filename, kind=kind, duration_ms=duration_ms
                ),
            )
    except Exception as exc:
        duration_ms = round((time.perf_counter() - started) * 1000, 2)
        log = logger.info if kind == "excerpt" else logger.warning
        log(
            "curriculum.fetch_failed",
            extra=log_extra(
                doc=physical_filename,
                kind=kind,
                url=url,
                duration_ms=duration_ms,
                error=str(exc)[:300],
            ),
        )
        text = ""

    _CACHE[physical_filename] = text
    return text


async def get_document_text(filename: str, *, subtopic: str | None = None) -> str:
    """Return text for one curriculum document.

    When ``subtopic`` is set, prefer the per-subtopic excerpt; fall back to
    the whole-book ``filename`` if the excerpt isn't in the bucket yet.
    Returns ``""`` for entries that aren't real files (URLs, empty values).
    """
    if not filename or filename.startswith("http"):
        logger.info(
            "curriculum.skip",
            extra=log_extra(doc=filename, reason="not_a_bucket_file"),
        )
        return ""

    if subtopic:
        excerpt = _excerpt_filename(filename, subtopic)
        text = await _fetch_with_cache(excerpt, kind="excerpt")
        if text:
            return text

    return await _fetch_with_cache(filename, kind="doc")


async def get_documents_text(
    filenames: list[str], *, subtopic: str | None = None
) -> str:
    """Concatenate text for multiple files into one prompt block."""
    if not filenames:
        logger.info("curriculum.lookup_empty", extra=log_extra(reason="no_filenames"))
        return ""

    logger.info(
        "curriculum.lookup_start",
        extra=log_extra(count=len(filenames), docs=filenames, subtopic=subtopic),
    )

    parts: list[str] = []
    used: list[str] = []
    missing: list[str] = []
    for f in filenames:
        text = await get_document_text(f, subtopic=subtopic)
        if text:
            parts.append(f"--- {f} ---\n{text}")
            used.append(f)
        else:
            missing.append(f)

    combined = "\n\n".join(parts)
    logger.info(
        "curriculum.lookup_done",
        extra=log_extra(
            requested=len(filenames),
            used=used,
            missing=missing,
            total_chars=len(combined),
        ),
    )
    return combined
